<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>cca846c5-07b9-45d8-bf24-fa88b52062c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.header-link--woAbP.title--1NHWk.gtm-login-click.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-wrapper']/div/div[2]/div/nav/div/ul[2]/li[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Login&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9dea7c23-3df9-4dd7-a1b5-8a79ec5cd751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>b0931031-47d1-4409-a089-4db9e4e80974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-link--woAbP title--1NHWk gtm-login-click active</value>
      <webElementGuid>d190730a-c107-4ae9-bccf-697d89647ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>9eadd620-75e0-48db-ac23-5fa73c5aeca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>44c3e8f6-6f7c-431e-ac77-5eeffc9f09d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/?login-modal=true&amp;redirect-url=/</value>
      <webElementGuid>e6a4e7ec-ada1-4b04-b793-15a1d54191f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>07ca61e2-912b-47ec-8622-a67c4d87c020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-wrapper&quot;)/div[@class=&quot;top-container--12FJu all justify-content-flex-start--1Xozy align-items-normal--vaTgD flex-wrap-nowrap--3IpfJ flex-direction-column--3aExp flex--3fKk1&quot;]/div[@class=&quot;only-desktop--2pxYG&quot;]/div[1]/nav[@class=&quot;nav--1qSMY background--2lR9B&quot;]/div[@class=&quot;justify-content-space-between--bjSys align-items-center--159cZ flex-wrap-nowrap--3IpfJ flex-direction-row--27fh1 flex--3fKk1&quot;]/ul[@class=&quot;nav-bar-list--201Xv&quot;]/li[@class=&quot;login-icon-container--3oQMU&quot;]/div[@class=&quot;justify-content-flex-start--1Xozy align-items-center--159cZ flex-wrap-nowrap--3IpfJ flex-direction-row--27fh1 flex--3fKk1&quot;]/a[@class=&quot;header-link--woAbP title--1NHWk gtm-login-click active&quot;]</value>
      <webElementGuid>48a31a0b-433e-4ab6-956e-f731c441a694</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-wrapper']/div/div[2]/div/nav/div/ul[2]/li[2]/div/a</value>
      <webElementGuid>d99c55b6-e81f-4197-8fd5-40629602573b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat'])[1]/following::a[1]</value>
      <webElementGuid>55b30ba3-0171-4c52-93e1-e823ca32b2b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='বাংলা'])[1]/following::a[2]</value>
      <webElementGuid>fd821154-7ca1-4f40-bbda-fbe711a15dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POST YOUR AD'])[1]/preceding::a[1]</value>
      <webElementGuid>44984b90-6a1d-4c82-84af-0bd84baa87b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/?login-modal=true&amp;redirect-url=/')])[2]</value>
      <webElementGuid>8dd94d48-a040-4a2c-8334-5433c36ff301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a</value>
      <webElementGuid>7cc8da32-1bfc-4c7a-871e-73428a94b06c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/?login-modal=true&amp;redirect-url=/' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>8e0975ee-cf47-4bb5-9df3-bf269b6532a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
