<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_You must fill out this field_password</name>
   <tag></tag>
   <elementGuidId>5f00be6c-311c-40c7-ae1f-32fec589da00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Password (at least 5 characters)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>372d076e-bff2-43d1-9b43-901f87545209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_password</value>
      <webElementGuid>e4d6388d-2317-4a6f-bcfa-b0a54548c5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>76cb3daa-c4f0-49c5-a377-a25677f2ed3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>90802092-6cb1-4382-8843-a29a4ab794e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>60ee77ce-f519-45b8-95da-126c543f7750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field--3A-bW themed-form-input--2Q2dw</value>
      <webElementGuid>5c6e0f77-d62c-4538-a71a-340847a25ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password (at least 5 characters)</value>
      <webElementGuid>df66c9f4-e48f-4171-9826-dbbe67d8cf72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_password&quot;)</value>
      <webElementGuid>7da625bf-4993-4658-b739-7a719028bfe2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_password']</value>
      <webElementGuid>e11cd7cd-c95b-460f-a31e-c672fc715109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>2344fe88-e56a-4993-abc2-51a706102301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input_password' and @name = 'password' and @type = 'password' and @placeholder = 'Password (at least 5 characters)']</value>
      <webElementGuid>40942538-5e0a-4027-acf3-d158b541bb9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
